#!/usr/bin/make -sf
## makefile
##
## Copyright 2016 Mac Radigan
## All Rights Reserved

.PHONY: demo demo-0 demo-1 demo-2
.DEFAULT_GOAL := demo

demo: demo-0 demo-1 demo-2

demo-0:
	$(MAKE) -C $@

demo-1:
	$(MAKE) -C $@

demo-2:
	$(MAKE) -C $@

## *EOF*
